import type { PyrometricCone } from '$lib/types/database';

export const PYROMETRIC_CONES: PyrometricCone[] = [
	{ name: 'Cone 022', display_order: 1,  temp_f: 1087, temp_c: 586,  color_fire: 'Dull Red',   firing_category: 'enamel_luster' },
	{ name: 'Cone 021', display_order: 2,  temp_f: 1112, temp_c: 600,  color_fire: 'Dull Red',   firing_category: 'enamel_luster' },
	{ name: 'Cone 020', display_order: 3,  temp_f: 1159, temp_c: 626,  color_fire: 'Dull Red',   firing_category: 'enamel_luster' },
	{ name: 'Cone 019', display_order: 4,  temp_f: 1252, temp_c: 678,  color_fire: 'Dull Red',   firing_category: 'enamel_luster' },
	{ name: 'Cone 018', display_order: 5,  temp_f: 1319, temp_c: 715,  color_fire: 'Dull Red',   firing_category: 'enamel_luster' },
	{ name: 'Cone 017', display_order: 6,  temp_f: 1360, temp_c: 738,  color_fire: 'Dull Red',   firing_category: 'enamel_luster' },
	{ name: 'Cone 016', display_order: 7,  temp_f: 1422, temp_c: 772,  color_fire: 'Red',        firing_category: 'enamel_luster' },
	{ name: 'Cone 015', display_order: 8,  temp_f: 1456, temp_c: 791,  color_fire: 'Red',        firing_category: 'enamel_luster' },
	{ name: 'Cone 014', display_order: 9,  temp_f: 1485, temp_c: 807,  color_fire: 'Red',        firing_category: 'enamel_luster' },
	{ name: 'Cone 013', display_order: 10, temp_f: 1539, temp_c: 837,  color_fire: 'Cherry Red', firing_category: 'bisque_lowfire' },
	{ name: 'Cone 012', display_order: 11, temp_f: 1582, temp_c: 861,  color_fire: 'Cherry Red', firing_category: 'bisque_lowfire' },
	{ name: 'Cone 011', display_order: 12, temp_f: 1607, temp_c: 875,  color_fire: 'Orange',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 010', display_order: 13, temp_f: 1657, temp_c: 903,  color_fire: 'Orange',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 09',  display_order: 14, temp_f: 1688, temp_c: 920,  color_fire: 'Orange',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 08',  display_order: 15, temp_f: 1728, temp_c: 942,  color_fire: 'Orange',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 07',  display_order: 16, temp_f: 1789, temp_c: 976,  color_fire: 'Orange',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 06',  display_order: 17, temp_f: 1828, temp_c: 998,  color_fire: 'Orange',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 05',  display_order: 18, temp_f: 1888, temp_c: 1031, color_fire: 'Orange',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 04',  display_order: 19, temp_f: 1945, temp_c: 1063, color_fire: 'Yellow',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 03',  display_order: 20, temp_f: 1987, temp_c: 1086, color_fire: 'Yellow',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 02',  display_order: 21, temp_f: 2016, temp_c: 1102, color_fire: 'Yellow',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 01',  display_order: 22, temp_f: 2046, temp_c: 1119, color_fire: 'Yellow',     firing_category: 'bisque_lowfire' },
	{ name: 'Cone 1',   display_order: 23, temp_f: 2079, temp_c: 1137, color_fire: 'Yellow',     firing_category: 'mid_fire' },
	{ name: 'Cone 2',   display_order: 24, temp_f: 2088, temp_c: 1142, color_fire: 'Yellow',     firing_category: 'mid_fire' },
	{ name: 'Cone 3',   display_order: 25, temp_f: 2106, temp_c: 1152, color_fire: 'Yellow',     firing_category: 'mid_fire' },
	{ name: 'Cone 4',   display_order: 26, temp_f: 2124, temp_c: 1162, color_fire: 'Yellow',     firing_category: 'mid_fire' },
	{ name: 'Cone 5',   display_order: 27, temp_f: 2167, temp_c: 1186, color_fire: 'Yellow',     firing_category: 'mid_fire' },
	{ name: 'Cone 6',   display_order: 28, temp_f: 2232, temp_c: 1222, color_fire: 'White',      firing_category: 'mid_fire' },
	{ name: 'Cone 7',   display_order: 29, temp_f: 2262, temp_c: 1239, color_fire: 'White',      firing_category: 'high_fire' },
	{ name: 'Cone 8',   display_order: 30, temp_f: 2280, temp_c: 1249, color_fire: 'White',      firing_category: 'high_fire' },
	{ name: 'Cone 9',   display_order: 31, temp_f: 2300, temp_c: 1260, color_fire: 'White',      firing_category: 'high_fire' },
	{ name: 'Cone 10',  display_order: 32, temp_f: 2345, temp_c: 1285, color_fire: 'White',      firing_category: 'high_fire' }
];
